---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    # Keep the actions under the template updated as well
    directory: '/{{cookiecutter.project_dest}}'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
