---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        exclude: '{{cookiecutter.project_dest}}/*'
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
        exclude: '{{cookiecutter.project_dest}}/*'
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: name-tests-test
      - id: trailing-whitespace
  - repo: https://github.com/broadinstitute/mirrors-pylama
    rev: v1.0.1
    hooks:
      - id: pylama
        exclude: '{{cookiecutter.project_dest}}/*'
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.24.2
    hooks:
      - id: yamllint
        args:
          - -s
        exclude: '{{cookiecutter.project_dest}}/*'
