---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: mixed-line-ending
      - id: name-tests-test
      - id: trailing-whitespace
{% if cookiecutter.use_pylama== 'y' -%}
  - repo: https://github.com/broadinstitute/mirrors-pylama
    rev: v1.0.2
    hooks:
      - id: pylama
{% endif -%}
{% if cookiecutter.use_ruff== 'y' -%}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
{% endif -%}
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.34.0
    hooks:
      - id: yamllint
        args:
          - -s
