---
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
cache: pip
sudo: false
before_install:
  - pip install pipenv --upgrade
install:
  - pipenv lock
  - pipenv sync --dev
script: pipenv run green -r -vvv
branches:
  only:
    - main
jobs:
  include:
    - stage: preflight
      python: '3.6'
      install:
        - pipenv install --dev
      script:
        # - pipenv check
        - yamllint . -s
        - pylama -v .
stages:
  - preflight
  - test
