---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/poetry-linting.yml@v1.4.1
{% if cookiecutter.use_ruff== 'y' %}
    with:
      use_pylama: false
      use_ruff: true
{% endif %}
  unit-tests:
    uses: broadinstitute/shared-workflows/.github/workflows/poetry-unit-tests.yml@v1.4.1
    with:
      python_package_name: {{cookiecutter.project_slug}}
