---
name: 'test_deploy'

'on':
  push:
    branches:
      - 'main'

jobs:
  pypi_test_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/python-test-deploy-to-pypi.yaml@v3.2.0
    secrets:
      pypi_test_token: {% raw %}${{ secrets.PYPI_TEST_TOKEN }}{% endraw %}
