---
name: 'test_deploy'

'on':
  push:
    branches:
      - 'main'

jobs:
  pypi_test_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/poetry-test-deploy.yml@v1.4.1
    secrets:
      pypi_test_token: {% raw %}${{ secrets.PYPI_TEST_TOKEN }}{% endraw %}
