---
name: 'test_deploy'
permissions:
  contents: read
  pull-requests: read
'on':
  push:
    branches:
      - 'main'

jobs:
  pypi_test_deploy:
    uses: broadinstitute/shared-workflows/.github/workflows/python-test-deploy-to-pypi.yaml@v5.0.1
    secrets:
      pypi_test_token: {% raw %}${{ secrets.PYPI_TEST_TOKEN }}{% endraw %}
