---
name: 'checks'
permissions:
  contents: read
  pull-requests: read
'on':
  pull_request:
    branches: ['*']

jobs:
  pre-commit:
    uses: broadinstitute/shared-workflows/.github/workflows/pre-commit.yaml@v5.0.0
